CREATE TABLE user (
  id INT AUTO_INCREMENT NOT NULL,
  username VARCHAR(10) UNIQUE NOT NULL,
  password CHAR(60) NOT NULL,
  address VARCHAR(320) UNIQUE NOT NULL,
  major VARCHAR(50) NOT NULL,
  image TINYINT NOT NULL DEFAULT 0,
  theme TINYINT NOT NULL DEFAULT 0,
  creator BOOLEAN NOT NULL DEFAULT TRUE,
  participant BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY(id)
);